# Generated by Django 3.2.25 on 2026-06-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='exit', upload_to='products/'),
            preserve_default=False,
        ),
    ]
